export const LOAD_LOCAL_DATA_SUCCESS = 'LOAD_LOCAL_DATA_SUCCESS';
export const LOAD_LOCAL_DATA_FAILURE = 'LOAD_LOCAL_DATA_FAILURE';
export const SAVE_LOCAL_DATA = 'SAVE_LOCAL_DATA';
export const FORM_UPDATE = 'FORM_UPDATE';
export const CREATE_GOAL = 'CREATE_GOAL';